### ISSUE TITLE
Tracking issue for bounty

### ISSUE THREAD

**Issue by bmann** [vic-en/pretix-eth-payment-plugin#4]
The original bounty description that is linked to Gitcoin is here: https://github.com/spadebuilders/community/issues/30

We can use this issue for tracking progress.

- [x] support ETH
- [x] support DAI
- [x] display a configured event wallet address
- [x] watch for an incoming payment linked to the order
- [x] communicate back the successful transaction to indicate that the order is paid

Non-feature related tasks:
- [x] creating a Github repo
- [x] releasing the code under Apache 2.0
- [x] check in current version of code

**Comment by vic-en** [comment]
I've successfully completed the bounty. Kindly review and let me know if there are any issues.
